---
title: "Lassen FIA Exploratory Graphs"
author: "Alexis Bernal"
date: "3/9/2020"
output: word_document
---

```{r}
library(here) #Call on files from Collins_Pine-master R project
library(tidyverse) #Data wrangling and manipulation
library(ggthemes) #Manipulate aesthetics of ggplot
```

#Importing d_FIA data from Lassen_FIA_Processing.Rmd to visualize plot data

```{r}
#Setting theme for figures
theme_set(theme_bw() + 
            theme(text = element_text(size = 12, family="serif"), 
        strip.background = element_blank()))

#Importing FIA plot data
FIA_graphs <- read.csv(here("Data/Derived", "d_FIA.csv"))

#Creating a column designating land ownership
#Codes < 40 are Federal- and State-owned
#Code = 40 is Private- an Native-owned
FIA_BA <- FIA_graphs %>%
  mutate(ownership = ifelse(OWNGRPCD < 40, "Federal/State",
                            ifelse(OWNGRPCD == 40, "Private/Native", NA)))

#Separating dataframes by ownership
Federal_BA <- FIA_BA %>%
  filter(ownership == "Federal/State")

Private_BA <- FIA_BA %>%
  filter(ownership == "Private/Native")

#Creating a color palette for histogram
palette.1 <- c(rep("firebrick3", 5), 
          rep("sienna2", 5), 
          rep("tan1",5),
          rep("khaki1", 5), 
          rep("lightskyblue1", 5),
          rep("steelblue", 5))

###########################################################################
#Live BA
###########################################################################

#Histogram of live BA
ggplot(FIA_BA, aes(BALIVE_sqmha)) + 
  geom_histogram(color = "black",
                 fill = palette.1) + 
  xlab(bquote("Live BA"~(m^2~ha^-1))) +
  ylab("Count") + 
  ggsave(here("Figures/Lassen-Plumas", "BALive.png"),
         width = 6, height = 4, dpi = 500)

#Histogram of live BA by ownership
ggplot(Private_BA, aes(BALIVE_sqmha)) + 
  geom_histogram(color = "black",
                 fill = palette.1) + 
  geom_histogram(data = Federal_BA, aes(BALIVE_sqmha),
                 color = "black",
                 fill = palette.1,
                 alpha = 0.5,
                 linetype = "dashed") + 
  xlab(bquote("Live BA"~(m^2~ha^-1))) +
  ylab("Count") + 
  ggsave(here("Figures/Lassen-Plumas", "BALive_ownership.png"),
         width = 6, height = 4, dpi = 500)

#Density plot of live BA by ownership
ggplot(FIA_BA, aes(BALIVE_sqmha, fill = ownership)) + 
  geom_density(alpha = 0.5) + 
  scale_fill_manual(values = c("goldenrod2",
                               "dodgerblue3")) + 
  xlab(bquote("Live BA"~(m^2~ha^-1))) +
  coord_cartesian(expand = FALSE) + 
  ylab("Density") +
  theme(legend.title = element_blank()) +
  ggsave(here("Figures/Lassen-Plumas", "BALive_density_ownership.png"),
         width = 6, height = 4, dpi = 500)

##############################################################################
#Fir-Pine Ratio
##############################################################################

#Histogram of Fir-Pine ratio
ggplot(FIA_BA, aes(AB_PI)) + 
  geom_histogram(color = "black",
                 fill = palette.1) + 
  xlab("Fir-Pine Ratio") +
  ylab("Count") + 
  ggsave(here("Figures/Lassen-Plumas", "Fir_Pine.png"),
         width = 6, height = 4, dpi = 500)  
  
#Histogram of Fir-Pine ratio by ownership
ggplot(Private_BA, aes(AB_PI)) + 
  geom_histogram(color = "black",
                 fill = palette.1) + 
  geom_histogram(data = Federal_BA, aes(AB_PI),
                 color = "black",
                 fill = palette.1,
                 alpha = 0.5,
                 linetype = "dashed") + 
  xlab("Fir-Pine Ratio") +
  ylab("Count") + 
  ggsave(here("Figures/Lassen-Plumas", "Fir_Pine_ownership.png"),
         width = 6, height = 4, dpi = 500)

#Density plot of Fir-Pine ratio by ownership
ggplot(FIA_BA, aes(AB_PI, fill = ownership)) + 
  geom_density(alpha = 0.5) + 
  scale_fill_manual(values = c("goldenrod2",
                               "dodgerblue3")) + 
  xlab("Fir-Pine Ratio") +
  coord_cartesian(expand = FALSE) + 
  ylab("Density") +
  theme(legend.title = element_blank()) +
  ggsave(here("Figures/Lassen-Plumas", "Fir_Pine_density_ownership.png"),
         width = 6, height = 4, dpi = 500)

#############################################################################
#TPH
#############################################################################

#Creating a datframe to graph TPH
#Gathering columns (long format) to designate diameter classes
#Removing entries where TPH = 0
FIA_density <- FIA_BA %>%
  group_by(PLT_CN) %>%
  gather(., "DBH.class", "TPH", 34:37) %>%
  filter(TPH != 0) %>%
  ungroup() %>%
  mutate(dbh = ifelse(DBH.class == "DENS_12plus", "All Trees",
                      ifelse(DBH.class == "DENS_12_24", "12-24in",
                             ifelse(DBH.class == "DENS_24_36", "24-36in",
                                    ifelse(DBH.class == "DENS_36plus", ">= 36in", NA)))))

#Reordering diameter classes for graph
FIA_density$dbh <- factor(FIA_density$dbh, levels = c("All Trees",
                                                      "12-24in",
                                                      "24-36in",
                                                      ">= 36in"))

#Separating dataframes by ownership
Federal_density <- FIA_density %>%
  filter(ownership == "Federal/State")

Private_density <- FIA_density %>%
  filter(ownership == "Private/Native")

#Establishing a color palette for facet histograms
palette.2 <- rep(c(rep("firebrick3", 5), 
          rep("sienna2", 5), 
          rep("tan1",5),
          rep("khaki1", 5), 
          rep("lightskyblue1", 5),
          rep("steelblue", 5)), 4)

#Histogram of TPH by diameter class
#Saving figure
ggplot(FIA_density, aes(TPH)) +
  geom_histogram(color = "black",
                 fill = palette.2,
                 origin = -0.5) + 
  facet_wrap(~dbh, scales = "free") + 
  ylab("Count") + 
  ggsave(here("Figures/Lassen-Plumas", "TPH.png"),
         width = 6, height = 4, dpi = 500)

#Histogram of TPH by diameter class AND ownership
#Saving figure
ggplot(Private_density, aes(TPH)) +
  geom_histogram(color = "black",
                 fill = palette.2,
                 origin = -0.5) + 
  facet_wrap(~dbh, scales = "free") + 
  geom_histogram(data = Federal_density, aes(TPH),
                 color = "black",
                 fill = palette.2,
                 alpha = 0.5,
                 origin = -0.5,
                 linetype = "dashed") + 
  ylab("Count") + 
  ggsave(here("Figures/Lassen-Plumas", "TPH_ownership.png"),
         width = 6, height = 4, dpi = 500)

#Density plot of TPH by diameter class AND ownership
ggplot(FIA_density, aes(TPH, fill = ownership)) + 
  geom_density(alpha = 0.5) + 
  scale_fill_manual(values = c("goldenrod2",
                               "dodgerblue3")) + 
  xlab("TPH") +
  coord_cartesian(expand = FALSE) + 
  ylab("Density") +
  facet_wrap(~dbh, scales = "free") +
  theme(legend.title = element_blank()) +
  ggsave(here("Figures/Lassen-Plumas", "TPH_density_ownership.png"),
         width = 6, height = 4, dpi = 500)


```

